### ISSUE TITLE
Responsive / Mobile behaviour

### ISSUE THREAD

**Issue by mrtzwlkr** [corygibbons/yuki#10]
It's a bit weird, but with resizing my browser (on desktop) I can see all the responsive behaviour. Which doesn't seem to work on an iPhone 6 for some reason → It just looks like desktop scaled on the mobile screen. Tiny type and tiny pictures.

**Comment by ghoseandco** [comment]
+1

**Comment by corygibbons** [comment]
Thanks for the heads up, I'll look into this.
